.Dd September 21, 2018
.Dt MID 1
.Os
.Sh NAME
.Nm mid
.Nd list message ID of files
.Sh SYNOPSIS
.Nm
.Op Ar msg
.Op Ar <sequence
.Sh DESCRIPTION
.Nm
uses the
.Xr notmuch 1
database to find the message ID of a filename.
It reads the filenames of the messages from the standard input or uses an
.Xr mmsg 7
specified
.Ar sg
and outputs the message ID on standard output.
The message ID is prefixed with the "id:", and escaped in accordance with Xapian search query escaping, allowing it to be easily piped into other
.Xr notmuch 1
utilities.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr notmuch 1 ,
.Xr mblaze 7
.Sh AUTHORS
.An Danny O'Brien Aq Mt danny@spesh.com
.Sh LICENSE
.Nm
is in the public domain.
.Pp
To the extent possible under law,
the creator of this work
has waived all copyright and related or
neighboring rights to this work.
.Pp
.Lk http://creativecommons.org/publicdomain/zero/1.0/
