.Dd September 21, 2018
.Dt MTAGS 1
.Os
.Sh NAME
.Nm mtags
.Nd list tags of messages.
.Sh SYNOPSIS
.Nm
.Op Fl t
.Op Fl h
<
.Ar sequence
.Sh DESCRIPTION
.Nm
lists the
.Xr notmuch 1
tags for messages. It reads the filenames of the messages from the standard
input, and outputs its tags on standard output, separated by spaces.
.Pp
The options are as follows:
.Bl -tag -width -indent
.Pp
.It Fl t
List the tags in a form suitable for feeding to
.Xr notmuch-tags 1
as a batch file. It will prefix each tag with a plus sign, and add '--'
followed by a search term that matches the message to the end of the line. This can be altered with, for example,
.Xr sed 1
, to add or remove tags.
.Pp
.It Fl h
Output usage guidance.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr notmuch 1 ,
.Xr mblaze 7
.Sh AUTHORS
.An Danny O'Brien Aq Mt danny@spesh.com
.Sh LICENSE
.Nm
is in the public domain.
.Pp
To the extent possible under law,
the creator of this work
has waived all copyright and related or
neighboring rights to this work.
.Pp
.Lk http://creativecommons.org/publicdomain/zero/1.0/
